#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AliDemir_UserControlLinqToSql
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TurkeyProvinces")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertProvince(Province instance);
    partial void UpdateProvince(Province instance);
    partial void DeleteProvince(Province instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::AliDemir_UserControlLinqToSql.Properties.Settings.Default.TurkeyProvincesConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Province> Provinces
		{
			get
			{
				return this.GetTable<Province>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Province")]
	public partial class Province : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ProvinceID;
		
		private string _ProvinceName;
		
		private System.Nullable<int> _PlateCode;
		
		private System.Data.Linq.Binary _Images;
		
		private System.Nullable<int> _PlaceToVisitID;
		
		private System.Nullable<int> _WhatFamousID;
		
		private System.Nullable<int> _PopulationID;
		
		private System.Nullable<int> _RegionID;
		
		private System.Nullable<int> _TransportationServiceID;
		
		private System.Nullable<int> _PartyID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProvinceIDChanging(int value);
    partial void OnProvinceIDChanged();
    partial void OnProvinceNameChanging(string value);
    partial void OnProvinceNameChanged();
    partial void OnPlateCodeChanging(System.Nullable<int> value);
    partial void OnPlateCodeChanged();
    partial void OnImagesChanging(System.Data.Linq.Binary value);
    partial void OnImagesChanged();
    partial void OnPlaceToVisitIDChanging(System.Nullable<int> value);
    partial void OnPlaceToVisitIDChanged();
    partial void OnWhatFamousIDChanging(System.Nullable<int> value);
    partial void OnWhatFamousIDChanged();
    partial void OnPopulationIDChanging(System.Nullable<int> value);
    partial void OnPopulationIDChanged();
    partial void OnRegionIDChanging(System.Nullable<int> value);
    partial void OnRegionIDChanged();
    partial void OnTransportationServiceIDChanging(System.Nullable<int> value);
    partial void OnTransportationServiceIDChanged();
    partial void OnPartyIDChanging(System.Nullable<int> value);
    partial void OnPartyIDChanged();
    #endregion
		
		public Province()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProvinceID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ProvinceID
		{
			get
			{
				return this._ProvinceID;
			}
			set
			{
				if ((this._ProvinceID != value))
				{
					this.OnProvinceIDChanging(value);
					this.SendPropertyChanging();
					this._ProvinceID = value;
					this.SendPropertyChanged("ProvinceID");
					this.OnProvinceIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProvinceName", DbType="NVarChar(50)")]
		public string ProvinceName
		{
			get
			{
				return this._ProvinceName;
			}
			set
			{
				if ((this._ProvinceName != value))
				{
					this.OnProvinceNameChanging(value);
					this.SendPropertyChanging();
					this._ProvinceName = value;
					this.SendPropertyChanged("ProvinceName");
					this.OnProvinceNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlateCode", DbType="Int")]
		public System.Nullable<int> PlateCode
		{
			get
			{
				return this._PlateCode;
			}
			set
			{
				if ((this._PlateCode != value))
				{
					this.OnPlateCodeChanging(value);
					this.SendPropertyChanging();
					this._PlateCode = value;
					this.SendPropertyChanged("PlateCode");
					this.OnPlateCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Images", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Images
		{
			get
			{
				return this._Images;
			}
			set
			{
				if ((this._Images != value))
				{
					this.OnImagesChanging(value);
					this.SendPropertyChanging();
					this._Images = value;
					this.SendPropertyChanged("Images");
					this.OnImagesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlaceToVisitID", DbType="Int")]
		public System.Nullable<int> PlaceToVisitID
		{
			get
			{
				return this._PlaceToVisitID;
			}
			set
			{
				if ((this._PlaceToVisitID != value))
				{
					this.OnPlaceToVisitIDChanging(value);
					this.SendPropertyChanging();
					this._PlaceToVisitID = value;
					this.SendPropertyChanged("PlaceToVisitID");
					this.OnPlaceToVisitIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WhatFamousID", DbType="Int")]
		public System.Nullable<int> WhatFamousID
		{
			get
			{
				return this._WhatFamousID;
			}
			set
			{
				if ((this._WhatFamousID != value))
				{
					this.OnWhatFamousIDChanging(value);
					this.SendPropertyChanging();
					this._WhatFamousID = value;
					this.SendPropertyChanged("WhatFamousID");
					this.OnWhatFamousIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PopulationID", DbType="Int")]
		public System.Nullable<int> PopulationID
		{
			get
			{
				return this._PopulationID;
			}
			set
			{
				if ((this._PopulationID != value))
				{
					this.OnPopulationIDChanging(value);
					this.SendPropertyChanging();
					this._PopulationID = value;
					this.SendPropertyChanged("PopulationID");
					this.OnPopulationIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegionID", DbType="Int")]
		public System.Nullable<int> RegionID
		{
			get
			{
				return this._RegionID;
			}
			set
			{
				if ((this._RegionID != value))
				{
					this.OnRegionIDChanging(value);
					this.SendPropertyChanging();
					this._RegionID = value;
					this.SendPropertyChanged("RegionID");
					this.OnRegionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransportationServiceID", DbType="Int")]
		public System.Nullable<int> TransportationServiceID
		{
			get
			{
				return this._TransportationServiceID;
			}
			set
			{
				if ((this._TransportationServiceID != value))
				{
					this.OnTransportationServiceIDChanging(value);
					this.SendPropertyChanging();
					this._TransportationServiceID = value;
					this.SendPropertyChanged("TransportationServiceID");
					this.OnTransportationServiceIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PartyID", DbType="Int")]
		public System.Nullable<int> PartyID
		{
			get
			{
				return this._PartyID;
			}
			set
			{
				if ((this._PartyID != value))
				{
					this.OnPartyIDChanging(value);
					this.SendPropertyChanging();
					this._PartyID = value;
					this.SendPropertyChanged("PartyID");
					this.OnPartyIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
