//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Town
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Town()
        {
            this.Villages = new HashSet<Village>();
        }
    
        public int TownID { get; set; }
        public string TownName { get; set; }
        public byte[] Images { get; set; }
        public int ProvinceID { get; set; }
        public int PlaceToVisitID { get; set; }
        public int WhatFamousID { get; set; }
        public int PopulationID { get; set; }
        public int TransportationServiceID { get; set; }
        public int PartyID { get; set; }
    
        public virtual PlacesToVisit PlacesToVisit { get; set; }
        public virtual Province Province { get; set; }
        public virtual RulingParty RulingParty { get; set; }
        public virtual TransportationService TransportationService { get; set; }
        public virtual WhatFamou WhatFamou { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Village> Villages { get; set; }
    }
}
