//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMDbClient.ProductServiceReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductServiceReference.ProductDataServiceSoap")]
    public interface ProductDataServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Login(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<string> LoginAsync(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/List", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable List(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/List", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ListAsync(string key);
        
        // CODEGEN: Generating message contract since message InsertRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CRMDbClient.ProductServiceReference.InsertResponse Insert(CRMDbClient.ProductServiceReference.InsertRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert", ReplyAction="*")]
        System.Threading.Tasks.Task<CRMDbClient.ProductServiceReference.InsertResponse> InsertAsync(CRMDbClient.ProductServiceReference.InsertRequest request);
        
        // CODEGEN: Generating message contract since message UpdateRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CRMDbClient.ProductServiceReference.UpdateResponse Update(CRMDbClient.ProductServiceReference.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        System.Threading.Tasks.Task<CRMDbClient.ProductServiceReference.UpdateResponse> UpdateAsync(CRMDbClient.ProductServiceReference.UpdateRequest request);
        
        // CODEGEN: Generating message contract since message DeleteRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CRMDbClient.ProductServiceReference.DeleteResponse Delete(CRMDbClient.ProductServiceReference.DeleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<CRMDbClient.ProductServiceReference.DeleteResponse> DeleteAsync(CRMDbClient.ProductServiceReference.DeleteRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AutoHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Insert", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public CRMDbClient.ProductServiceReference.AutoHeader AutoHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public double price;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int stock;
        
        public InsertRequest() {
        }
        
        public InsertRequest(CRMDbClient.ProductServiceReference.AutoHeader AutoHeader, string name, double price, int stock) {
            this.AutoHeader = AutoHeader;
            this.name = name;
            this.price = price;
            this.stock = stock;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string InsertResult;
        
        public InsertResponse() {
        }
        
        public InsertResponse(string InsertResult) {
            this.InsertResult = InsertResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public CRMDbClient.ProductServiceReference.AutoHeader AutoHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public double price;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int stock;
        
        public UpdateRequest() {
        }
        
        public UpdateRequest(CRMDbClient.ProductServiceReference.AutoHeader AutoHeader, int id, string name, double price, int stock) {
            this.AutoHeader = AutoHeader;
            this.id = id;
            this.name = name;
            this.price = price;
            this.stock = stock;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string UpdateResult;
        
        public UpdateResponse() {
        }
        
        public UpdateResponse(string UpdateResult) {
            this.UpdateResult = UpdateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public CRMDbClient.ProductServiceReference.AutoHeader AutoHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int id;
        
        public DeleteRequest() {
        }
        
        public DeleteRequest(CRMDbClient.ProductServiceReference.AutoHeader AutoHeader, int id) {
            this.AutoHeader = AutoHeader;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string DeleteResult;
        
        public DeleteResponse() {
        }
        
        public DeleteResponse(string DeleteResult) {
            this.DeleteResult = DeleteResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProductDataServiceSoapChannel : CRMDbClient.ProductServiceReference.ProductDataServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductDataServiceSoapClient : System.ServiceModel.ClientBase<CRMDbClient.ProductServiceReference.ProductDataServiceSoap>, CRMDbClient.ProductServiceReference.ProductDataServiceSoap {
        
        public ProductDataServiceSoapClient() {
        }
        
        public ProductDataServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductDataServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductDataServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductDataServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Login(string userName, string password) {
            return base.Channel.Login(userName, password);
        }
        
        public System.Threading.Tasks.Task<string> LoginAsync(string userName, string password) {
            return base.Channel.LoginAsync(userName, password);
        }
        
        public System.Data.DataTable List(string key) {
            return base.Channel.List(key);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ListAsync(string key) {
            return base.Channel.ListAsync(key);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRMDbClient.ProductServiceReference.InsertResponse CRMDbClient.ProductServiceReference.ProductDataServiceSoap.Insert(CRMDbClient.ProductServiceReference.InsertRequest request) {
            return base.Channel.Insert(request);
        }
        
        public string Insert(CRMDbClient.ProductServiceReference.AutoHeader AutoHeader, string name, double price, int stock) {
            CRMDbClient.ProductServiceReference.InsertRequest inValue = new CRMDbClient.ProductServiceReference.InsertRequest();
            inValue.AutoHeader = AutoHeader;
            inValue.name = name;
            inValue.price = price;
            inValue.stock = stock;
            CRMDbClient.ProductServiceReference.InsertResponse retVal = ((CRMDbClient.ProductServiceReference.ProductDataServiceSoap)(this)).Insert(inValue);
            return retVal.InsertResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CRMDbClient.ProductServiceReference.InsertResponse> CRMDbClient.ProductServiceReference.ProductDataServiceSoap.InsertAsync(CRMDbClient.ProductServiceReference.InsertRequest request) {
            return base.Channel.InsertAsync(request);
        }
        
        public System.Threading.Tasks.Task<CRMDbClient.ProductServiceReference.InsertResponse> InsertAsync(CRMDbClient.ProductServiceReference.AutoHeader AutoHeader, string name, double price, int stock) {
            CRMDbClient.ProductServiceReference.InsertRequest inValue = new CRMDbClient.ProductServiceReference.InsertRequest();
            inValue.AutoHeader = AutoHeader;
            inValue.name = name;
            inValue.price = price;
            inValue.stock = stock;
            return ((CRMDbClient.ProductServiceReference.ProductDataServiceSoap)(this)).InsertAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRMDbClient.ProductServiceReference.UpdateResponse CRMDbClient.ProductServiceReference.ProductDataServiceSoap.Update(CRMDbClient.ProductServiceReference.UpdateRequest request) {
            return base.Channel.Update(request);
        }
        
        public string Update(CRMDbClient.ProductServiceReference.AutoHeader AutoHeader, int id, string name, double price, int stock) {
            CRMDbClient.ProductServiceReference.UpdateRequest inValue = new CRMDbClient.ProductServiceReference.UpdateRequest();
            inValue.AutoHeader = AutoHeader;
            inValue.id = id;
            inValue.name = name;
            inValue.price = price;
            inValue.stock = stock;
            CRMDbClient.ProductServiceReference.UpdateResponse retVal = ((CRMDbClient.ProductServiceReference.ProductDataServiceSoap)(this)).Update(inValue);
            return retVal.UpdateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CRMDbClient.ProductServiceReference.UpdateResponse> CRMDbClient.ProductServiceReference.ProductDataServiceSoap.UpdateAsync(CRMDbClient.ProductServiceReference.UpdateRequest request) {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<CRMDbClient.ProductServiceReference.UpdateResponse> UpdateAsync(CRMDbClient.ProductServiceReference.AutoHeader AutoHeader, int id, string name, double price, int stock) {
            CRMDbClient.ProductServiceReference.UpdateRequest inValue = new CRMDbClient.ProductServiceReference.UpdateRequest();
            inValue.AutoHeader = AutoHeader;
            inValue.id = id;
            inValue.name = name;
            inValue.price = price;
            inValue.stock = stock;
            return ((CRMDbClient.ProductServiceReference.ProductDataServiceSoap)(this)).UpdateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRMDbClient.ProductServiceReference.DeleteResponse CRMDbClient.ProductServiceReference.ProductDataServiceSoap.Delete(CRMDbClient.ProductServiceReference.DeleteRequest request) {
            return base.Channel.Delete(request);
        }
        
        public string Delete(CRMDbClient.ProductServiceReference.AutoHeader AutoHeader, int id) {
            CRMDbClient.ProductServiceReference.DeleteRequest inValue = new CRMDbClient.ProductServiceReference.DeleteRequest();
            inValue.AutoHeader = AutoHeader;
            inValue.id = id;
            CRMDbClient.ProductServiceReference.DeleteResponse retVal = ((CRMDbClient.ProductServiceReference.ProductDataServiceSoap)(this)).Delete(inValue);
            return retVal.DeleteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CRMDbClient.ProductServiceReference.DeleteResponse> CRMDbClient.ProductServiceReference.ProductDataServiceSoap.DeleteAsync(CRMDbClient.ProductServiceReference.DeleteRequest request) {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<CRMDbClient.ProductServiceReference.DeleteResponse> DeleteAsync(CRMDbClient.ProductServiceReference.AutoHeader AutoHeader, int id) {
            CRMDbClient.ProductServiceReference.DeleteRequest inValue = new CRMDbClient.ProductServiceReference.DeleteRequest();
            inValue.AutoHeader = AutoHeader;
            inValue.id = id;
            return ((CRMDbClient.ProductServiceReference.ProductDataServiceSoap)(this)).DeleteAsync(inValue);
        }
    }
}
