//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TurkeyProvincesCFEntities : DbContext
    {
        public TurkeyProvincesCFEntities()
            : base("name=TurkeyProvincesCFEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PlacesToVisit> PlacesToVisits { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<RulingParty> RulingParties { get; set; }
        public virtual DbSet<Town> Towns { get; set; }
        public virtual DbSet<TransportationService> TransportationServices { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Village> Villages { get; set; }
        public virtual DbSet<WhatFamou> WhatFamous { get; set; }
    }
}
