//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Province
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Province()
        {
            this.Towns = new HashSet<Town>();
            this.Users = new HashSet<User>();
        }
    
        public int ProvinceID { get; set; }
        public string ProvinceName { get; set; }
        public Nullable<int> PlateCode { get; set; }
        public byte[] Images { get; set; }
        public Nullable<int> PlaceToVisitID { get; set; }
        public Nullable<int> WhatFamousID { get; set; }
        public Nullable<int> PopulationID { get; set; }
        public Nullable<int> RegionID { get; set; }
        public Nullable<int> TransportationServiceID { get; set; }
        public Nullable<int> PartyID { get; set; }
    
        public virtual PlacesToVisit PlacesToVisit { get; set; }
        public virtual Population Population { get; set; }
        public virtual RulingParty RulingParty { get; set; }
        public virtual Region Region { get; set; }
        public virtual TransportationService TransportationService { get; set; }
        public virtual WhatFamou WhatFamou { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Town> Towns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
    }
}
