//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Village
    {
        public int VillageID { get; set; }
        public string VillageName { get; set; }
        public byte[] Images { get; set; }
        public Nullable<int> TownID { get; set; }
        public Nullable<int> PopulationID { get; set; }
    
        public virtual Population Population { get; set; }
        public virtual Town Town { get; set; }
    }
}
